# -*- coding: utf-8 -*-
"""JUAN FELIPE SOUZA OLIVEIRA - SegundoTVCControle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YKEJyIZ7YTPWYl8TiU-r_YkPhA1hso4j

Questão1) Considere:

$G_1(s) = K \cdot \frac{s+0.1}{s+0.5}$

$G_2(s) = \frac{10}{s \cdot (s+1)}$

$H(s)=1$

A função de transf. de ramo direto, FTRD, é $G_1(s) \cdot G_2(s)$.

A função de transf. de malha aberta, FTMA, é $G_1(s) \cdot G_2(s) \cdot H(s)$.

a) Calcule o valor do ganho K para que a Margem de Fase seja $50^o$.

b) Qual é margem de ganho, frequencia de cruzamento de ganho e frequencia de cruzamento de fase do sistema para o ganho K calculado na letra A.

$\underline{\text{Observação}: } Resolva a letra a e b manualmente e cole na célula abaixo o documento digitalizado.

c) Desenvolva um programa em Python para calcular o valor K. E, a partir do valor de K, calcular a margem de ganho, frequencia de cruzamento de ganho e a frequencia de cruzaento de fase.
"""

!pip install control

import numpy as np
from control import *

#Dado no enunciado a margem de fase (MF) = 50°
MF = 50
#Cálculo da margem da fase é dada por: MF = 180 - phi
phi = MF - 180


#-90 arctan(10wcg)  -arctan(wcg) -arctan(wwcg) = phi

#Teremos: -90 arctan(10wcg)  -arctan(wcg) -arctan(wwcg) = phi

# arctan(10wcg)  -arctan(wcg) -arctan(2wcg) = A
A = phi + 90

# tan(A) * (1.4 wcg^2 + 0.05) / (-0.35* wcg + wcg^3) = 0


tanA = np.tan(A*np.pi/180)
raizes = np.roots(np.array([1, 1.4*tanA, -0.35 , 0.05*tanA]))
wcg = raizes[0]

# |GH|wcg = 1
# wcg^6 + 1.25wcg^4 + 0.25wcg^2 - 100Kwcg^2 -K^2 = O

B = pow(wcg,6) + (1.25*pow(wcg,4)) +(0.25*pow(wcg,2))
C = (100*pow(wcg,2))-1

K = np.sqrt(B/C)

#K = (wcg * np.sqrt(pow(wcg,2) +1)* np.sqrt(pow(wcg,2) + 0.25))/(10 * np.sqrt(pow(wcg,2) +0.01))


print("k = ", K)
print("wcg = ",wcg)


#Conclusão da Questão utilizando margin(gh)

num = [10*K, K]
den = [1,1.5,0.5,0]

gh = tf(num,den)

[Mg, MF, wcf, wcg] = margin(gh)

print(f"A margem de ganho é {Mg:7.3}")
print(f"A margem de fase é {MF:7.3}")
print(f"A frequencia cruzamento de ganho é {wcg:7.3} rad/s")
print(f"A frequencia cruzamento de fase é {wcf:7.3} rad/s")

"""Questão 2) Considere:

$𝐺_c(𝑠)=K_p \cdot (1+T_d \cdot s)$ (Controlador Proporcional)

$𝐺(𝑠)=\frac{1}{s^2}$ (Veículo Espacial)

$𝐻(𝑠)=1$

A função de transf. de ramo direto, FTRD, é $𝐺_c(𝑠)⋅𝐺(𝑠)$.

A função de transf. de malha aberta, FTMA, é $𝐺_c(𝑠)⋅𝐺(𝑠)⋅𝐻(𝑠)$.

Utilizando o Python, faça o que se pede:

a) Determine o valor de $K_p$ e $T_d$ para que o sistema em malha fechada tenha uma banda passante entre 0.4 e 0.5 rad/s e a margem de fase do sistema seja de $50^o$.

b) Calcule a Margem de Ganho, Margem de Fase, Freq. Cruzamento de Fase e Freq. de Cruzamento de Ganho do sistema.



"""

import numpy as np
from control import *

#Dado no enunciado a margem de fase (MF) = 50°
MF = 50
#Cálculo da margem da fase é dada por: MF = 180 - phi
phi = MF - 180

#Dada a banda passante entre 0.4 e 0.5 temos a média para realizarmos a programação
wcg = 0.45

# 50 = 180-180+arctan(td*wcg)
#arctan(td*wcg) = 50
# td * wcg = tan(50)

tan50 = np.tan(50*np.pi/180)
Td = tan50/wcg


# Dada que a frequência de cruzamento é aquela an qual |GH| = 1
# Kp^2*(wcg^2Td + 1)/(wcg^4) = 1

Kp = pow(wcg,2) / (np.sqrt(pow(wcg*Td,2) + 1))

##Conclusão da Questão 2 utilizando margin(gh)

num = [ Kp*Td , Kp ]
den = [ 1, 0, 0]

gh = tf(num,den)

[MG, MF, wcf, wcg] = margin(gh)

print(f"O valor de Td é {Td:7.3}")
print(f"O valor de kp é {Kp:7.3}")
print(f"A margem de ganho é {MG:7.3}")
print(f"A margem de fase é {MF:7.3}")
print(f"A frequencia cruzamento de ganho é {wcg:7.3} rad/s")
print(f"A frequencia cruzamento de fase é {wcf:7.3} rad/s")